### ISSUE TITLE
no config?

### ISSUE THREAD

**Issue by Willem07** [Aureljz/WhenDungeonsArise--Forge#11]
Why are there no configs after 1.18? I want the structures to appear less frequently in the release version 1.19, how do I do this through a datapack?

**Comment by TheEscaper** [comment]
I'm having the same issue

**Comment by Aureljz** [comment]
The whole mod can be configured using datapacks, which is why we include a datapack template on all curseforge downloads. I recommend you to check it. Inside those folders, you'll be able to modify spacing and separation to tweak spawnrates. (data/dungeons_arise/worldgen/structure_set/minor_structures.json). For instance, spacing = 100, separation = 80 would make minor structures rarer.
Additionally here's a comment I left on curseforge some days ago:

1. Download the datapack template for your version. It'll be a zip file. You can turn it into a normal folder to edit it easily, if you want. The latest one for forge should be [here](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise/files/4203094).

2. Find the files you want to change. To change structure rarity, you'll need to tweak "minor_structures.json" and "major_structures.json". You can find these on the folder you've downloaded: data/dungeons_arise/worldgen/structure_set/minor_structures.json

3. Following the message above, you edit the file (you can open this using any text editor) and change numbers for 'separation' and 'spacing' (they're at the end of the text file). If you want structures to be more common, decrease the values. If you want them to be rare, increase values.

Example: (This would make all structures a lot more common)

"spacing": 10,
"separation": 5,

4. Place the datapack on your world folder (on 'datapacks' or on creation), or use a global datapack mod so it's always active. Yung's Paxi and Openloader are two useful datapack mods.

It seems like a lot of steps, but you just have to change two numbers. Datapacks can also change loot tables, structure pieces, achievements and more, which is why they're useful for modpack devs.

**Comment by TheEscaper** [comment]
Wow! Thanks for explaining

**Comment by jumbojordan21** [comment]
Is there anyway to make dungeons arise spawn in modded biomes because im hosting a server with my friends asnd they are not spawning in terralith biomes o plenty and tectonic world structures
